import '../styles/globals.scss'
import type {AppProps} from 'next/app'
import Head from "next/head";
import HeaderComponent from "../components/header-component";
import {useRouter} from "next/router";
import {Toolbar} from "@mui/material";
import {config} from "@fortawesome/fontawesome-svg-core";


config.autoAddCss = false;


function MyApp({Component, pageProps}: AppProps) {

    const router = useRouter();
    const path = router.pathname;


    var isHomepage: boolean = true
    if (path !== "/") {
        isHomepage = false;
    }

    return (
        <>
            <Head>
                <title>Luca Faccio Web Resume</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            </Head>
            <HeaderComponent/>
            <main>
                <Toolbar color={"transparent"}/>
                <Component {...pageProps} />
            </main>

            <footer>
                <div className={"footer-copyright"}>©2022 Luca Faccio. All right reserved.</div>
            </footer>
        </>
    )
}

export default MyApp
